version: '3'
services:
  a build: 
   dmin:
      context: .
      dockerfile : DockerfileAdminManagement
      ports:
        -"8082:8082"
  book:
    build: 
      context: .
      dockerfile : DockerfileBook
      ports:
        -"8081:8081"
  discovery:
    build: 
      context: .
      dockerfile : DockerfileDiscoveryServer
      ports:
        -"8761:8761"
  student:
    build: 
      context: .
      dockerfile : DockerfileAdminStudent
      ports:
        -"8080:8080"
  front:
    build:
      context: .
      dockerfile: DockerfileFront
      ports:
        -"4200:4200"
  mysql:
    build: .
    image: mysql
    
      
